### ISSUE TITLE
Command line and web service czml converters

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/czml-writer#12]
- Command line tool(s) to convert from all supported formats to czml.
- REST web service(s) to convert from all supported formats to czml.  We also want to host this like http://cesium.agi.com/.
- Both the command line and web service should have sensible defaults and customization options based on the input.

Include:
- Unit tests.
- User documentation.
- Way to execute the web service without writing code, e.g. like https://dev.twitter.com/console.
- Update the Quick Start and Contributor's Guide.

For related discussion, see https://groups.google.com/forum/#!topic/cesium-dev/TcaCJAbgsCE.

See @kring and @mramato for technical guidance.

**Comment by shunter** [comment]
At this point I intend to limit the scope of this project to solely CZML generation, rather than providing converters.  Rather than converting to CZML, it would be better to provide direct support for formats in Cesium.  As such, this issue is obsolete.
