### ISSUE TITLE
Ability to specify orientation with VelocityOrientationProperty

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/czml-writer#140]
Requested on the forum: https://groups.google.com/forum/#!searchin/cesium-dev/paul%7Csort:relevance/cesium-dev/3u4nMD_emiw/AAxmyGzfCAAJ

**Comment by mramato** [comment]
Did you mean `Ability to specify VelocityOrientationProperty with CZML`?  Otherwise I'm not sure what you're asking for here.

**Comment by mramato** [comment]
Nevermind, I reread the title in the context of this being in the czml-writer repository.

**Comment by shunter** [comment]
This will require Cesium changes as well.

**Comment by ggetz** [comment]
Should I cross list the issue in both or close this one?
