### ISSUE TITLE
Czml 一条轨道上可以有不同颜色或不同宽度的线吗

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/czml-writer#156]
![default](https://user-images.githubusercontent.com/33933148/52622951-0a334a00-2ee6-11e9-8a6b-3c77abacf8e9.JPG)
我可以将czml中卫星的轨道分成不同的颜色或不同的宽度吗？

**Comment by emackey** [comment]
Closing as duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/7561
