### ISSUE TITLE
czml satellite path 

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/czml-writer#157]
![image](https://user-images.githubusercontent.com/33933148/52837140-959c1d80-3128-11e9-91a6-25927935ee61.png)
如何让czml中卫星轨道  实现上面的效果。分段显示颜色

**Comment by emackey** [comment]
Sorry, this is currently not supported.  The feature request is being tracked in https://github.com/AnalyticalGraphicsInc/cesium/issues/4393.
