### ISSUE TITLE
Update to Csharp libraries to .Net Standard/Core

### ISSUE THREAD

**Issue by AshitakaLax** [AnalyticalGraphicsInc/czml-writer#177]
.net framework is dying, January 10, 2023
https://stackoverflow.com/questions/58732338/when-is-end-of-life-for-dotnet-framework-4-5-2

Please update to the latest .net standard and .net Core library.

**Comment by shunter** [comment]
This library already supports .NET Core using [.NET Framework compatibility mode](https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps#net-framework-compatibility-mode).
