### ISSUE TITLE
quick start fail

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [AnalyticalGraphicsInc/czml-writer#178]
When I select root directory `\czml-writer\Java`, I can't click "finish" button. And eclipse remind me "no projects are found to import".

Then I add `.classpath` and `.project` file to `\czml-writer\Java`. It works, I can click "finish" button now. But I can't click "Build All" button. I have no idea with this problem. Hope someone can help me. Thanks!

The content in `.classpath` and `.project`  is listed below:
- `.classpath`  
  ```
		<?xml version="1.0" encoding="UTF-8"?>
		<classpath>
			<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-13">
				<attributes>
					<attribute name="module" value="true"/>
				</attributes>
			</classpathentry>
			<classpathentry kind="output" path="bin"/>
		</classpath>
  ```
- `.project`  
  ```
		<?xml version="1.0" encoding="UTF-8"?>
		<projectDescription>
			<name>Java</name>
			<comment></comment>
			<projects>
			</projects>
			<buildSpec>
				<buildCommand>
					<name>org.eclipse.jdt.core.javabuilder</name>
					<arguments>
					</arguments>
				</buildCommand>
			</buildSpec>
			<natures>
				<nature>org.eclipse.jdt.core.javanature</nature>
			</natures>
		</projectDescription>
  ```

**Comment by shunter** [comment]
This project no longer uses Eclipse.  I've updated the wiki page [Quick-Start](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Quick-Start) to describe using IntelliJ IDEA or Gradle to build.
