### ISSUE TITLE
Document PolylineVolume

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/czml-writer#180]
Cesium added support for PolylineVolume a few months ago, in https://github.com/CesiumGS/cesium/pull/8841, but it's not listed [on the wiki](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Packet).  As far as I can tell, that's still the authoritative place to go for CZML syntax, right?

**Comment by thw0rted** [comment]
Reading over the linked PR, this is my first pass at a Typescript interface, which should more or less map one-to-one with the docs format on the wiki:

````ts
export interface PolylineVolume {
    positions?: PositionList;
    shape?: PositionList;
    show?: boolean;
    cornerType?: {cornerType: CornerTypeValue} | ReferenceProperty;
    fill?: boolean;
    material?: Material;
    outline?: boolean;
    outlineColor?: ColorValue | ReferenceProperty;
    outlineWidth?: number;
    granularity?: number;
    shadows?: ShadowModeProperty | ReferenceProperty;
    distanceDisplayCondition?: DistanceDisplayConditionProperty | ReferenceProperty;
}
````

**Comment by astrojuanlu** [comment]
JSON schema lives here, and `PolylineVolume` is still not present: https://github.com/AnalyticalGraphicsInc/czml-writer/tree/master/Schema

**Comment by shunter** [comment]
Added in #183.
