### ISSUE TITLE
PolylineArrowMaterial documentation is wrong

### ISSUE THREAD

**Issue by mhaberler** [AnalyticalGraphicsInc/czml-writer#181]
the property name should be polylineArrow rather than arrow
the property type is a SolidColorMaterial, not a color

btw: how do I edit the wiki to file a PR?

**Comment by shunter** [comment]
I checked and the documentation correctly uses `polylineArrow`

https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/PolylineMaterial

https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/PolylineArrowMaterial

`Color` is also correct here. Materials do not contain other materials.
