### ISSUE TITLE
viewsheds for sensors in cesium-analytics

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/czml-writer#182]
Sensors in the proprietary `cesium-analytics` package will gain the ability to show viewsheds in the February release. 

This capability is controlled through new properties in `RectangularSensorGraphics`, `ConicSensorGraphics`, and `CustomPatternSensorGraphics`:
* `showViewshed` - `Boolean`
* `viewshedVisibleColor` - `Color`
* `viewshedOccludedColor` - `Color`
* `viewshedResolution` - `Number` - pixel resolution for the textures backing the viewshed technique
* `classificationType` - `ClassificationType` - for determining if the viewshed shows on terrain, on 3D Tiles, or on both.

**Comment by shunter** [comment]
Added in #184.  Note that `classificationType` was not actually added to sensors in the `cesium-analytics` code.
