### ISSUE TITLE
how to use czml-writer???

### ISSUE THREAD

**Issue by LitianshiGIS** [AnalyticalGraphicsInc/czml-writer#185]
During my learning journey, I tried many methods but still couldn't run the project. If possible, I hope someone can help me and explain to me how to use this file. (Both .NET and JAVA are fine)😀😀

**Comment by emackey** [comment]
There's a sample here:  https://github.com/AnalyticalGraphicsInc/czml-writer/tree/master/DotNet/ExampleCesiumLanguageServer
