### ISSUE TITLE
czml zip archives

### ISSUE THREAD

**Issue by kiselev-dv** [AnalyticalGraphicsInc/czml-writer#186]
Would it be worth to extend czml definition to support archives same way as KMZ extends KML? 

It will be useful to reference resources like material textures, billboard images, models instead of using data: urls to embed them in czml documents.    

I've made a small demo in sandcastle which loads czmlz archive. [Sandcastle CZMLZ parsing](https://sandcastle.cesium.com/#c=lXpnl6PGl/dX6cdnz3HPwW5EFDjtkqMCCJCExy8QOSMy2p3v/iB1T4+6xzP2nxeSqu7vxrp1K6DeqR/62B/8+uH3h8IfHhi/ibv8ybr1PX78wb21mbJonbjw648/fPj1Y/Gx6Ge+k9P4OGrH1cz68QfPaZ1fnKrKYtdp47IAS7f125+btvad/Ndn7E8m17A0rbHU7dmpESRR7x7l+uEJ1sVjsMTPoUaFaJUaNJMaKIqh6DQsvR0dW40ZL2iKYgNKoyh+plGinrmI1h2Rqj0xZHqC19Bpb3Wf5dhHkD6Vq4HjjD6gDjG7isLjYt2fjvl5l+aV1FZsOYWTHfIqLdMjvNhYAU6wmglbW3fZ9FXhgVYMC6a/Twqo2MBmvy1BzXF9DzuiwdGQ/O3FrgHsUNuFAGgSPC2n44WQ+aSwLnUCHzglkmgdEkPXVVAdCS0/zMXhvEG5Kha6lXTk20RLIOmU1/lJsFfnbi2TdZBoO5lnao0WmiV7EbaOIa+k1GZ3ec6oMddpl7BaHVfmUWcQsZETdOPSkZCsqVCKp81A9VqQK4F6FvjTuosx4rzotbOlQ0u2OwGCGbSsBRG4mpK1cohPipWpC9KWWCj3bayvK81OET9sLYUJuXFdd1AdYATYnxcbX7RxGPZa1S+QQTV7rxA4vWu4I2CTzlRxB9XRBpw5Iqy1wpwEL2ghtgETqVvVAyjrNq7KdVzncaySfK27xJ6GGG01d6TXJOHCr8Z1YR/WC7WgOxvNNCN110xU3nKGNTNJ56/5RN8SSaNC4fp9zrMRucqhsmHHZ5f5RyfNOtV4RfuKCXozjSFtWed40+eXbU6QsLB0rTHhUtlW8SOZ70TD66yTVxkREF5Iq+VJKE33gVSVbUeMtmevQWOp1qXjbY2Oy429rEIHXOe4HgJysRVROYlNVW2SQ7Id9HQVUwIAkLDKDMPACly1gwrFrJwpo9xaPyGhRtRBWx/xoge9hceVIACxk+ZGEr9ZEGTBj85mG58l0toJRgFLbkAue3HqToxYBKM6HqiMdpkcSAhOWCUTYELlOV6h4xiTwFLQubMA9fbikK9KBNNFAa2FHScu0U7yp4Cq1wh2TGg0bNUzyqRKu1CP+x2sZLWOtrTM7PCUZAVxXQCd4IqoNWRRVYbORoU3rsGpxwijjkOEpaC6PPj45lyCTYpCqKyJaQWGF95fHMbDikE09HLCu914UVt5HwOKtcsPvOxN4imjdoBppPbO5NKisGeWcz9xFXvcaBDnniWY1Y4DKERCP9vM+ZNI1cESG91935xi02dsBMFMZj+FvQNs8fOyDjLpsHQ7wuRwLF6qvlJWCSfwvoKW0rQ1vB2odbp7ViJXKfAIY0JgWpHkok5795hsux4BR6Qb9N7PNQbp2gt21miwiWqmIRrtcGZRPeMIKID21RQPYHVeHCpviqxpWU/cyGupTDHnrVID2qJO2PyAgiJhoWXvbIx864ZDDJFLpDugvXa66A3ZLi2BxGWKDwDjOAVTdQ4mZY/QB+kQw8R+1HBlh6ZrxCHV5oQBOF6wxXn0dhvR8ovu7OMZXHbl2hKIQXFT1CQhI2Zj2dWB7UIA+rWgbaAVihhoHRcAyWiJuUWg03kO12pCjjYuotF0IWlXEz3HDvbLprA6okJwi0WWlo3Ve31XJXt9HdvarssjtPEHE5PHxQ5XAi225OVFXwlx3S8QSEBjZQgFf4PxgzzIE6YdOhMV7cyTgmlnIbZ3Kc74YYIxZAcni6o/V8R+qELM0VDRaTtoZ8P0EpIcduXaWwFKzcjoY4/3wXNbw+6Wp4K9X1SuhmPkLmrPRpJ0xkppGTuKAGtRgUxT9fgqIlh+DyHW+tSPkm0hZFTvd/2loWXe2I4QaJ6QMh+PMhfKquBXLaX4Xc9W6SKmAdwi4b2w2SLr3Z7B/V1XFHRNpaoMZmvEX64JM8OVrQ+b5gkooLU3HEV0y6ksY5kZK+1S4AyvNQ1VTJYP4GR1JDyv8fyjMY0S3uGR5REjFm1c1xAojDVsUanqPdOSaerv6I5Xpv7so0hJqu1hSI4MgdQq7psqWonBKSegkKdToxoyt5l6zJN9H9OTejAojOY4roB2MmuOebdaK9UKo+DIk7H9GRrlpo5xS8SlNTJAQgoDyDpEwfV6ro9RlfG5kDNFB4SHS68c8f1+cwhX/nEEIM93oAHO4uJE2qJjlNESx7dakVIeJYwqv1hHO1HByWq3182ep9gtpJFsKOSGfTSGhNX4BLGyKRm0S7PmI0JlaC7E6y2TIuyaR3W/xowLGEmsmK+CtsNPRJcV3sEgqhNRofO6fW4WDH6ulmJo2J1onrfSioBiMzxmDQ8Zvt6cN4tCCGWxZkkOkPhhWZo3PdqC2geTgx/gc0ZmDUmqW1EP+IvihgsSulBz5gxCh28ww+T2m2OOeQg5uSu4YgxEj/OlHO6tRlWW/sU0axHYik5ljmEKyUfrlC7Vs8YmArWAD0rZM+62hhzRgMlDtPLlsG4ul1F1RbIxsNpH9otRO283XuaKRIuYusRsNzEGL5uDuwHZwXVJ3yQx2NJIh9zK0oIA+Zy2rSWD7sqmcyVuW2wYSA4qd++GbF92elQAVcv0Qh6swLE/e6u+6qfVud7PZYlSozB0cQuDziYU7nR22IBpfK4zaJEbBOucin23X6PkoE6hbW4EbrcSGd5DQ68kbf2AZaRYgjSYEHYKbayVs9WovW+DRXZyBn7sj1BheaJj8Uammpm2gKa5CF/8BVJX6I4x7dWhWh4MQLd9zCxgFpbBhqPFZssrYJQQkrKctMZhTHqQoYPLufCpXx/GY7uOY6ez8qzqAWQnrIqCOkMdsYujVrFSoCPAeqOllmYVS1J299ay5GkkoewghAet7xYMfYENsWrkTTKtsOVmIpAcqcpC90/rfKUxYxciK1n2LXcwIDsnDqOS5n3t4Uc0u2jQubzMGwE0MknUOkLlJOD4Ykmw+QRlc022uoJCqDUfHAd4dYpH11wna7SASFm68JCvQINpld6oy1IDOCZpbDMMn31DpIkA5xGdXG67oRjxktAMvByiS7HbzSkQXA7+MfbFi3bxscsBaBmqR4DS3TMqNzBrI273pocXBUZa28AuLGVSlXHbCnDuUldZOCJSYkVU804RrWWDlD2exQ8LYL+zXYUALQHRVCPOMmZfKBhRnLT6su55UGElAlmhFlI0QzbrKfmJ1EKB26pL2IN9Qk74Qlni7TRBvrSMI2yDFMtDegKDkOgISTQIxikJ2GE6zTB1BxmpWtGMHCczhSDdbMWSBxlUc6DeXc0s5ul9kgfd1Lt1zrENhAI7ZBrTXoF0GDuX/LK7AFa71gp04NO+XxQ519G9OY6Os0VJG2id4Xj04MlYUGkoWktEM4Ulph/FQBbTpR+0vt6TADsth9DbDvI5uSBhXXDVPAtGx7dQTz8VtjwucdncQ/lh7VexEhYVkwcyTKiEcboEcXrZrpcrfo1hizSkdGilyKnvwiJdDieMjEnIMR1iMyL6xhiwvOCzdBeJl4wf7RrbPo+POy/8GDUBiTWNHUXzYEIxFjaEJOEXU76mRVqbrNwbunCUL8d63nD2lLRJG8baOynKQRinp0d+5TmO2TO8fsHAEYPT/kSCyx0CW5i2HkINcFFqj4gnw1ekBbdby7S89yC3XhneIY7ZZl6WtEBhB144dmQXR2xn+IJC8UqOrEYTwJDCvcge6u0CUltsCIlSgw3Fqcu4BUp4YiiBJi4hDStelJzbxdYLyMilNlBQokt3EhYJYg8+76QuQ2KOb7a8biP8en/B9m22Ap3qAuLVgRxCynOjjuD6DbVhPVmiaNFEUZYSz3WiLbCqTs8wockbl1S6WmxoSWmXNb3rsgNXb+LUX4Hq1KvY0iJrqDUUUCY5cLOik/lcZJclCPrGirqO09DnhNAiSSafhI3TGhUeJPPxbuOxhCDSDrZe0RAXx31GVXO21WASVBBmby1n15nLuWKCxxV7nZcFILoU4pWpZEohd3B3/rY5CoOYnZjW6I+8z8wnFpRai0pkB8czd+Qq3W5Sq668+bC5ghdLJMOPLk5yPcgcg9n/lkApvU/BvR5pEQWwMT1Xo81ZEOxwUR0tDL8A8Ia2NZEhDicnn5Rt5cZLyJuYZcSVGQ/UblfZSLAjWtP3yaYwRBDZbS8JRd3yfAVUeWwKELGz02QKE3fsM3SNHhraX423nGBStRlnNpGvOCgNo9OeRGhvh3RucaHgHvd9lxkpjZEIAMVcxMkCtcD686HeOmm/qoPV9kRXp3OvBiG0j0h7nj066hjZZWxOIU4KJYin2y3fMnCk7gjcaitEU+i9izCJoZUZQSHrVFfmgwQWij1Rk2pQDMRhcA5toIh42+VVka4NoiQKoF7XhNcciNNwbkBy3njzBQ/aAsdwXIK6+TYhFTBxT4U38m6AOwkIVOG5kn2U6qz9gc+JQcq1bNIzwEXEftf3/HxUGfyl0ahqLQc9sLLxqGdrzyQL0Nr4VtQ4/lSAx5N6AMDGA0CI3BWNe0jbZkXpnr/enhaLnlvznZqingR4uawepHKkkxhKLIULiRFuj7ydMS6xjYzJIidF4tpNWKR0M0xqsd+6h/4AmzY21mAXWBsXRCnukMCn9bo5t4zLQBsxSBS5LCWIahvyiDGwDldJ3Jl10WkpsV8SKS4KABJohL5epMtNmwJaYJMat6eWTaA0BBZmpr/YwuzqDODbPb3MIFeqMxWss0lB5JCxpVjIFXZJc8NOoYhynqz7Zgp1wIaMTpKtIF6FyYnqapCTuDgdNYSWg5hjmZQ++B0/Noc9CzWaSXBBFbB2S7bg6GVm0OkUvSMH3bXM82TNakQvRbR0MvzVGlcEX0Gi/bIlDjEyxPPeOxLm46DfR/PsAQRvlMB1NICjcuEOMKIT+ZqQsU71iQ0D8CuE731BjcC4dflFiBI8qRqY2pQbOQItMNydZAO++C0uq3u32mX1fHw+DS04eDajAandrhH6dq9Ay7qJcXUqh2FGq5QmgdT4D/dPjPba4CSW1G5N+vneIV/jp/3QMyEVvkBoip4bHDyQflNDg0AZJxbCp/5AHel1sz3UCunSJtfQVDKfQqjr1UZI2ZIiXretJ15qr/dXyMDNklxK/mJHGCo7+nax8Q/3Wl/ZIrkn1JdutkBouoBvtjBzConxvS1MuLox4UcsMQ9bPvS0252LfL2QoaW3tqg7Og65b9/FDCX1GkmNOlISXeqKlDTtkQ5XR5fo3sXGolVaOz7jB4ql5kyjKNZnn0P/+8cfXm8ZV3HuG1PlNw+/P/zvx+Lh9jh9/MvDxx/mo6BfguPPeXP79fGHnz4DTnl1BcS5E/rg3LgnXeAr6f6qcvz5dIkr+A7kRvl7UF94T3nzc9TmWeRn9xLdprmCW39swfn3G0p/R+nvKF7pvleQN0NZe/eYZy/fWjp33kH8qnkPqcqmbdw6rto7XJD19wGbm3fEMA6+BGtu3JMuX1sQzrG6g8wBefXxGpy3pOxbtNgtvyi9xTZ267Ipg/ZpJhV3yKTIqq+tSJze+flK+jmIM/8eXvnhF8nX1hvit2k50t3UdF58S6qZ2tX3JufoXRDzCr0nOW307OubEb31AuMbx/PY+6JmbsRvafG3ieWd+nMXu2k7z417QIXcMb9zrkK/aXv1Hb9egvmZ9k7mt2mlV/3dBCqdJm6eysov5gnQ5X7RPlW138zfN8wbAc2/FNDMEhyviXy/fcPf/kv+a3beM4bhe8a56w5QecFXc867nzRVcZdkc+OeVDXfqCtVOfh1VcZF+wbe/kfwf1cMzu3386j+2sG5610a181Xyuau96D2a0ntfaia/i5Uc+MdfzMEX8/8JirddHB6fy5jThPdwa8j+VpvqsyJ7xOqva9ycyN4S/sO8TtCZzPua8bcvCfmzpuC0vw897yh929XsZl+zz9+XVHehmcuxO8Bb2uze/laRNK8mWdh9jxGeen5GXhtAa+I14XIb3235esy5+daWzi5/8tD0BXuVd7DY/DS9+HL+nx9rov3HLJ52f4MeGpL9Zq2jNP4j9f3iF/Az8D582mumW70CH78+PT458ePw1/Af3/4L/DDn9Bfb/C133Z18WVz8OfM+gXxabb9020HMa8kTXuN0yz95dXm3HgBBv5V1etrzA9PbeQXj3M5qmYu/+H3P+4detH4mfp0ysrTqxOfXnivne/4ni2Y2cqsv71l/d9Pv76nVnNk4+a2xfnzr1+/xP3h9kp2+0x9vFY5v9afJb3T8pINT+4Man39hnx8S/4s7gqjZztfQFeTP/z0NfTz+L6o/fBe25e4XMlPod9yRVvHfvP4JTP8555v8t70lPXD4zVX4tn7xa/z128PL3xPc9qEbTT3AcB3Zbym28w3XfPomf/P+G3SfP3EwcPj/7txPXlxPed4WU//qOn6PL6o+uPfgD+bl8/ZOlv3mrRPX8+rZ7lPX6bU//3f+7Xo7rX6bZv8b7R/TrCnqmuix/ukuum7psK38+p7z7O58+CzTus8fk6vawNHTV3a13E759jV8Q8/PVz/IvAfyn/OsOe58+fb2Pw1h/Iq8df/TNp7h98Vou8/n/4t+NOHf4P89OE5/v+E/fRt8ndIb+rFN938W5feSb2HfC51jx/+Ziiv5azM/KesDB9/vP4z5GrDjz+95t97XS9F9SUZn5wse/w76D/q/FJgZ1HjdH9U/PLMWWrq6i/3la0pu9r1vznjn0VnpetkM+cs9TPHU+3POwHXf/wxatt51wWCjVN4rtO0s/PPf5l5csscbP18xrV+A85B+HH+bp+uSzL447dG440z3ovGW/J/tuKva0n4bMev36rJn9eqm5h/HuBPbxadW726/QHo6TrBdjdVzZPjeX+zpLysqszsFvsKnhPA8R5fbb/z/HXXfW39+NdP3wr9s39mPR+H7v6WpL/4/fidEjKf2X65i/WPP30bWl2T5Ze3ufOtWfI3MfzwvVnyujOYf/zw0w+/Ne2U+X98RvxPnFdl3V6NfXx6usuTU+em/mx58zoBfgPvWX/z4v4h9n7/m39mPbjzdriZKUGXZbv4Mm/p//gNnPFfsV5HJy7Czexz5kxXWAT9oT53Pj09/QbOzb/nbMsyOzn1O8n/Hw)

Archive consist of: 

* document.czml
* test.png

and document.czml references test.png as a billboard image:
```
[{
    "id" : "document",
    "name" : "CZML Path",
    "version" : "1.0"
},
{
    "id": "f5c1a051-a47a-4af2-9aeb-63fc3623f33e",
    "position": {
        "cartographicDegrees": [-73.99534276863604,40.74398077607238,0]
    },
    "billboard":{
        "image": "test.png",
        "verticalOrigin":  "BOTTOM",
        "heightReference": "RELATIVE_TO_GROUND",
        "width":  50,
        "height": 50,
        "disableDepthTestDistance": 1000000000
    }
}]
```

It's only a draft showing that reading from zip archive and resolving urls inside archive is working.

**Comment by shunter** [comment]
Generally, you get better compression with less effort by simply using the browser's built-in, automatic gzip decompression. Even though it seems like the overhead of base64 data URLs (~33%) is a lot, the result compresses very well, making the actual overhead much lower. 

Also, because each .zip entry is individually compressed, you can't get any compression gains from redundancy across files either. Inlining all files into a single CZML is roughly analogous to solid compression which will produce better compression results. 

I did a quick test with your zip file (3.77 KB). After inlining the PNG into the CZML as a data URL and compressing with gzip, the result is 3.43 KB.  

The decisions made for KML/KMZ were a different era (decades ago) so they don't always make sense in a browser environment.

**Comment by bengoldstein** [comment]
The important benefit of the type of format that kiselev-dv is proposing is readability, which of course makes editing and maintenance easier too.
