### ISSUE TITLE
How does one Interpolate a Polyline

### ISSUE THREAD

**Issue by ChthonicOne** [AnalyticalGraphicsInc/czml-writer#187]
I am looking at ways to interpolate a Polyline to have it follow along perpendicularly to another path, ellipsoid, and billboard. The problem is that the 3 main ways to designate polyline points are not interpolatable according to your reference sheet. The only way to do it is the referenceListValue, which is not very well documented here, or at all in SandCastle.

How do I interpolate a Polyline such that I can have it extrapolate it's position and move it over time?

**Comment by shunter** [comment]
Generally the best way would be to define each vertex within the polyline as its own object with its own time-varying position, then define the polyline using references to the vertices. 

There is a Sandcastle example that demonstrates this with polygons, but the same approach works with polylines.

[Existing polygon example](https://sandcastle.cesium.com/?src=CZML%20Polygon%20-%20Interpolating%20References.html)

[Example modified to define a polyline instead](https://sandcastle.cesium.com/#c=5VZRb9owEP4rFnuhUghJIKFiFK2ikzap6qp12sMIDyYxYM2xke2kolP++2wCmR2g0O1xEUS57+47X+6+yC4gB8lLRsANmMYUgF/6BgBOhyBupSzJM0Rl3HIquEBcYEa1z3e9HVw6h8QNhRlOHhnZEExRzYcFxATOMcFyo+MCzw863nXH63/zo6Hnqd+PrgkOdmCdYb1LOdwvqCGBpapKGBgAHC0QRzRBCp7GrcJ/t49TudTSRdAEegYwc/aZyvppjfjjLuATwsuVHALJc1T7MygRx5BYZQhGcDphhHELBiCpsKmJATtk20+qkhY66QXdioZBaHXrz8WXc7hQy/kO8Byg7v6sEVM6f11K74LBHZayq+NsKaa3PJhLeUqDhW+IphqbMYLtyygxQY3fkiXjWK4yzbv//PDx9qtRtxV6h5YcKfX5tvvSCR1pC1qzZHWKbMQlkEu25HC9wklVhbDk4xlt6kSm1QtNw1OXYfuRTQxPEUPPa1D7ltUZ2D7DCBrEa5sYBSYxbBKtapvU8NSaUdig9iLvDS2qzdlZnQVndfYP6jg+9U4/dNXnE6h/vxrL+TJ7//HnYIkqamj4FUlbihocSNqWpm12LEkNwkbkq9K0y32DNGfvYxrTQu3pBUbPiKtdnaJnMEEC55n7fYu141aytSeMSqi2Uq73v60SxIrlJL2lWG9l9e5WXlVZt2w3hRI+sZyrHC5M0/Yu90SdIe5ql0sYTNv6XHFVkVtOayTkhqDxvvgPOFszLkHOSdt1uxJlayUpJLrzPPmJpJsIoak6dNQ1qaMUF0rTN0deAyQECqE8i5yQJ/yiDh7jUVfFH1B1fZguv6gDDYEbHbbyx/cV6LruqKvM40zJGJlDbmSuIn4D)

**Comment by ChthonicOne** [comment]
Thank you for your response. It might be good to have examples of how to build a reference in your project, as I couldn't find one previously.
