### ISSUE TITLE
Upgrade from .NET Framework to .NET

### ISSUE THREAD

**Issue by himby** [AnalyticalGraphicsInc/czml-writer#193]
The library would be more useful if the DotNet version was ported to .NET Standard, so both older and newer projects could use it without doing modifications.

**Comment by shunter** [comment]
Thanks for the suggestion. I'm working on the changes, however, the library already works with .NET Core (and therefore .NET 5+) without any changes, due to .NET Framework compatibility mode (with the exception of a warning which can be ignored).

**Comment by himby** [comment]
Thanks a lot! Great, that was a quick response.
