### ISSUE TITLE
CZML validator tries to request a non-existent jsonschema file when validating

### ISSUE THREAD

**Issue by jumpinjackie** [AnalyticalGraphicsInc/czml-writer#93]
The CZML validator does not currently work. Attempting to validate a fragment of czml will fail because it will 404 requesting ConicSensor.jsonschema again in some non-existent directory.

See attached screenshot:
![capture](https://cloud.githubusercontent.com/assets/563860/4200890/173f1c6c-3817-11e4-9511-ecdc67f0bb2f.PNG)

The CZML validator is hosted on IIS 7.5

**Comment by shunter** [comment]
The JSV validator was removed.  A working example of validating using Ajv in node.js is provided in:

https://github.com/AnalyticalGraphicsInc/czml-writer/blob/master/Schema/validate.js
